spring:
  application:
    name: api-gateway

#Customizado wiremock
#port:notNull 
#mappings: optional(default:src/test/resources)
wiremock:
  port: 8081 
  mappings: 'mock'

server:
  port: 8080
zuul:
  routes:
    wiremock:
      path: /wiremock/**
      url: http://localhost:${wiremock.port}